# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55774609de177d241f600ccafc236d1d21e00192ca242404abf3768c5d86448847f1edb97eddafa57573be9e6857c5a0c88103f1c77e2fdc235bedb609e22738

test:
  secret_key_base: 3c9eb80f53728a29c6d68aa8d88a356a2119a35d871c5b7e01f9d0c3c4af573a8c18fead1465c7c794e02fc1f74446445df637eb8a0759fd7bde41b6a8c3bc2c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
